apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: email-provider-loops
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: email-provider-loops
  ports:
    - name: webhook-https
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: metrics
      port: 8443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None